name:                aoc-day1
version:             0.1.0.0
github:              "thomaswhiteway/aoc-day1"
license:             BSD3
author:              "Thomas Whiteway"
maintainer:          "thomas.whiteway@gmail.com"
copyright:           "Copyright (c) 2020 Thomas Whiteway"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thomaswhiteway/aoc-day1#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  aoc-day1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
